### ISSUE TITLE
Question : does a destination 'site' need to be empty? or will it overwrite the destination ENV?

### ISSUE THREAD

**Issue by alphex** [pantheon-systems/terminus-site-clone-plugin#1]
Question : does a destination 'site' need to be empty? or will it overwrite the destination ENV?

Thanks!

**Comment by ataylorme** [comment]
@alphex the destination does not need to be empty. The destination environment will be overwritten with code, database and/or files (depending on the arguments).

Mind letting me know your use case? I'd love to hear how people are using the plugin.
