### ISSUE TITLE
terminus not finding plugin

### ISSUE THREAD

**Issue by boaterdan** [pantheon-systems/terminus-site-clone-plugin#12]
I've installed this plugin using all the various techniques (git clone, manually unzip, composer create project) and always the same result when I type 'terminus site:clone' and it says 'command "site:clone" is not defined'.  (BTW I tried the composer plugin and it doesn't recognize that either.)

I'm running Terminus 1.9.0.  There seems to be something missing to make Terminus look in the plugins folder.  I'm on Windows 10, which I know isn't officially supported, but I have Terminus itself running fine and just can't run plugins.  What is it that is supposed to make Terminus load plugins?

**Comment by ataylorme** [comment]
Hi, @boaterdan that sounds like a larger Terminus issue, not an issue with this plugin specifically. I would advise you to open an issue in the [Terminus repository](https://github.com/pantheon-systems/terminus) instead.

Though, as you said, Windows is not supported. I have heard of a few folks having success running Terminus in the [Linux subsystem for Windows](https://docs.microsoft.com/en-us/windows/wsl/install-win10) but I don't have any experience with that myself.

Another option would be to use a virtual environments. [Lando](https://docs.devwithlando.io/), for example, runs inside Docker and supports Terminus commands.
