### ISSUE TITLE
Couldn't use --yes for bash scripts with clone command, it doesn't work and requests confirmation any way

### ISSUE THREAD

**Issue by ulkayu** [pantheon-systems/terminus-site-clone-plugin#22]
commands example:
terminus site:clone $sourceSiteName.dev $sitename.dev  --yes
--yes doesn't work, requires operator action

**Comment by rijas-madurakuzhi** [comment]
You can use the 'yes' command
Eg:-
yes | terminus site:clone $sourceSiteName.dev $sitename.dev
