### ISSUE TITLE
PHP Fatal error:  Uncaught Error: Call to a member function get()

### ISSUE THREAD

**Issue by kyletaylored** [pantheon-systems/terminus-site-clone-plugin#35]
```
PHP Fatal error:  Uncaught Error: Call to a member function get() on null in ~/.terminus/terminus-dependencies-7422d8f8f1/vendor/pantheon-systems/terminus-site-clone-plugin/src/Commands/SiteCloneCommand.php:214
```

**Comment by jspellman814** [comment]
Tracking internally as BUGS-5608

**Comment by rolriley** [comment]
Hello,
I am getting same error on this command .. Any updates or Alternative to clone site with Terminus?
PHP Fatal error:  Uncaught Error: Call to a member function get() on null in /home/rolri/.terminus/terminus-dependencies-7422d8f8f1/vendor/pantheon-systems/terminus-site-clone-plugin/src/Commands/SiteCloneCommand.php:214
Stack trace:

**Comment by kporras07** [comment]
I was able to reproduce this only if I didn't use site.env as the argument for source and destination. Added an extra check in the linked PR.
